name: schedulenus
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.2.2 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    animate_do: ^3.1.2
    auto_size_text: ^3.0.0
    cached_network_image: ^3.3.0
    cloud_functions: ^4.5.8
    convex_bottom_bar: ^3.2.0
    cupertino_icons: ^1.0.2
    device_preview: ^1.1.0
    dio: ^5.3.3
    firebase_auth: ^4.15.0
    firebase_core: ^2.24.0
    flutter_riverpod: ^2.4.7
    flutter_svg: ^2.0.9
    form_validator: ^2.1.1
    google_fonts: ^6.1.0
    go_router: ^13.0.0
    readmore: ^2.1.0
    riverpod: ^2.4.6
    riverpod_annotation: ^2.3.1
    skeletonizer: ^1.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.4.6
    custom_lint: ^0.5.7
    flutter_lints: ^3.0.1
    riverpod_generator: ^2.3.7
    riverpod_lint: ^2.3.4

flutter:
    uses-material-design: true
    assets:
        - images/book-closed-svgrepo-com.svg
        - images/calendar-svgrepo-com.svg
